services:
  playlink-database:
    image: postgres
    hostname: database.playlink
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: "playlink"
      POSTGRES_PASSWORD: "playlink"
    ports:
      - "5432:5432"

  redis:
    image: bitnami/redis
    hostname: redis.playlink
    container_name: redis
    restart: always
    environment:
      REDIS_REPLICATION_MODE: "master"
      REDIS_PASSWORD: "playlink"
    ports:
      - "6379:6379"

networks:
  default:
    name: playlink
    driver: bridge
