services:

  playlink-database:
    image: postgres
    hostname: database.playlink
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: "playlink"
      POSTGRES_PASSWORD: "playlink"
    ports:
      - "5432:5432"

  playlink-database-admin:
    image: dpage/pgadmin4
    hostname: admin.database.playlink
    container_name: database-admin
    restart: always
    depends_on:
      - playlink-database
    environment:
      PGADMIN_DEFAULT_EMAIL: "playlink@playlink.com"
      PGADMIN_DEFAULT_PASSWORD: "playlink"
    ports:
      - "2345:80"

  redis:
    image: bitnami/redis
    hostname: redis.playlink
    container_name: redis
    restart: always
    environment:
      REDIS_REPLICATION_MODE: "master"
      REDIS_PASSWORD: "playlink"
    ports:
      - "6379:6379"

networks:
  default:
    name: playlink
    driver: bridge
